# Mint's Awesome Server Guide Configuration

title: Mint’s Awesome Server
author: Nate Cleveland
email: dubious.nate@gmail.com
description: >-
  🍀 The official guide for installing and joining Mint’s Awesome Server.
baseurl: "/mints-awesome-server" # the subpath of your site
url: "https://dubiousnate.github.io" # your GitHub Pages base URL
github_username: dubiousnate

# Optional social handles
# instagram_username: yourhandle
# linkedin_username: your-linkedin-id

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

sass:
  sass_dir: css
  style: compressed

favicon: /favicon.ico

# Exclude these files/folders from being processed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
